### ISSUE TITLE
Missing cover field.

### ISSUE THREAD

**Issue by Maan511** [thephpleague/oauth2-facebook#12]
Any reason the 'cover' field is left out of the fields array, in `getResourceOwnerDetailsUrl()`?

**Comment by SammyK** [comment]
Nope. Just hasn't been added yet. Would you like to send the PR? :) If not I can add it.

**Comment by Maan511** [comment]
Sorry for my late reply. You can just add it :)

**Comment by SammyK** [comment]
Added in 1.1.0. :)
