### ISSUE TITLE
Accessing the Facebook Graph to retrieve more info. 

### ISSUE THREAD

**Issue by MrCoding** [thephpleague/oauth2-facebook#13]
Dear All,

Probably I am in the completely wrong location to ask question about this nice piece of code but I am wondering if it is possible to retrieve other information about the user, maybe group posts etc?

Due to issues with the PHP SDK from Facebook I am not able to use those routines to authenticate users and so I tried this code. It worked with some little changes almost within 5 minutes.

(Please advice me when I am in the wrong location, or asking the wrong type of questions. I am completely new here and like to learn.)

For now thank you all for the great work and please enjoy your weekend!

**Comment by SammyK** [comment]
Hey @MrCoding! Once you obtain an access token from the Facebook provider, you can make calls to the Graph API using any HTTP client you like (e.g. Guzzle HTTP Client or [`file_get_contents()`](http://php.net/file_get_contents)).

Here's an example of getting photos of the authenticated user with `file_get_contents()`:

```php
$url = 'https://graph.facebook.com/v2.4/me/photos?access_token='.$accessToken;
$res = file_get_contents($url);
$data = json_decode($res, true);

var_dump($data);
```

Hope that helps!
