### ISSUE TITLE
Example comment for getExpires() in README.md implies duration rather than timestamp

### ISSUE THREAD

**Issue by hi2u** [thephpleague/oauth2-facebook#16]
The comment in the example in README.md is slightly inaccurate:

```php
// Number of seconds until the access token will expire, and need refreshing
var_dump($token->getExpires());
```

That comment kind of implies that the number given is how many seconds from now the expiry will occur (a duration in seconds).  

Rather the number given is the unix timestamp of when it expires.

Sorry, I know this is super pedantic, but I just thought it might worth re-wording in case new users get confused.

**Comment by SammyK** [comment]
Thanks for the feedback @hi2u. You're right, that's confusing. I've updated the docs. :)
