### ISSUE TITLE
Out of sync with 1.0

### ISSUE THREAD

**Issue by shadowhand** [thephpleague/oauth2-facebook#2]
Facebook client is currently broken when running against v1.0. I recently [made oauth2-google compatible](/thephpleague/oauth2-google/commit/13add491678580ecc10ca3b8bc4c856556aea76b). Quite a bit has changed, though not significantly, mostly just clean up of the internal API.

**Comment by SammyK** [comment]
Thanks for the heads up @shadowhand! I'll try to get this fixed by EOD Thursday. :)

**Comment by SammyK** [comment]
FYI: This issue is on hold until we can get [the constant issue addressed](https://github.com/thephpleague/oauth2-client/pull/294#discussion_r30260206). :)

**Comment by philsturgeon** [comment]
You’re a constant issue.

**Comment by SammyK** [comment]
Baha! This is very `true`.

**Comment by SammyK** [comment]
Refactored & updated docs. :)
