### ISSUE TITLE
Check graphApiVersion format

### ISSUE THREAD

**Issue by pmaselkowski** [thephpleague/oauth2-facebook#25]
Hi!

`graphApiVersion` param could be checked for proper format, to have
letter `v` at beginning:
v2.7 vs 2.7
This might help catch earlier if improper format is used.

**Comment by SammyK** [comment]
I would be OK with this if someone would like to make a PR for it! :)

**Comment by pmaselkowski** [comment]
Alright, added checks, it pretty annoyed me when had `2.4` in app configuration and facebook requests resulted in 404.

**Comment by SammyK** [comment]
Merged in #26. :)
