### ISSUE TITLE
Deprecated  field for versions v2.8

### ISSUE THREAD

**Issue by slince** [thephpleague/oauth2-facebook#27]
Hi
There is an error.

![image](https://cloud.githubusercontent.com/assets/3785826/19425242/a77f287c-9462-11e6-8744-cf1e4d7536ac.png)

**Comment by Chrico** [comment]
See also here about the deprecations in v2.8: https://developers.facebook.com/docs/apps/changelog?locale=en_US#v2_8_deprecations

The field `bio` has to be removed from `League\OAuth2\Client\Provider\Facebook::getResourceOwnerDetailsUrl`.

**Comment by medbejimbj** [comment]
Hi, could you  please merge this changes to be considered when  we lunch composer for this package  "thephpleague/oauth2-facebook"

**Comment by scolandrea** [comment]
I agree!
