### ISSUE TITLE
Facebook extended access tokens

### ISSUE THREAD

**Issue by farmnick** [thephpleague/oauth2-facebook#3]
Currently Facebook supports a function that allows the SDK to extend access tokens ( https://developers.facebook.com/docs/facebook-login/access-tokens#changingtokens ). Currently, this library only uses short term tokens. In the official SDK on line 219 the function starts: https://github.com/facebook/facebook-php-sdk-v4/blob/4.0-dev/src/Facebook/Entities/AccessToken.php

**Comment by SammyK** [comment]
Thanks for the feedback @farmnick! I brought this issue up in the [main repo](https://github.com/thephpleague/oauth2-client/issues/320) to see if any other providers need the same functionality.

**Comment by SammyK** [comment]
@farmnick The Facebook provider now has support for [extending access token lifetimes](https://github.com/thephpleague/oauth2-facebook#long-lived-access-tokens). Thanks for opening this issue! :)
