### ISSUE TITLE
Question:  FB redirect_uri error

### ISSUE THREAD

**Issue by norbertogomez** [thephpleague/oauth2-facebook#31]
Hello, I am getting an error while trying to get access token via:
```
$provider->getAccessToken("authorization_code", [
                "code" => $_GET["code"]
            ]);
```
Also I have this two functions to retrieve the Facebook authorization url:
```
            public static function getFbAuthURL() {
                $output = null;

                if (empty($fbCode = \Helpers\Session::getKey("fbcode"))) {
                    if (!empty($provider = self::getProvider())) {
                        $output = $provider->getAuthorizationUrl();
                    }
                }
                
                return $output;
            }
            
            public static function getProvider() {
                $output = null;

                if (!empty($configuration = self::getFBConfiguration())) {
                    if (!empty($provider = new \League\OAuth2\Client\Provider\Facebook([
                            'clientId'          => $configuration["clientId"],
                            'clientSecret'      => $configuration["clientSecret"],
                            'redirectUri'       => $configuration["redirectUri"], //https://shoppingmall-local.ventajon.com
                            'graphApiVersion'   => $configuration["graphApiVersion"],
                    ]))) {
                        $output = $provider;
                    }
                }
                
                return $output;
            }
```
This is what I get as url:
https://www.facebook.com/v2.8/dialog/oauth?state=E9UkxQZtCDfgwNaMHbEule42OSDC68jk&scope=public_profile%2Cemail&response_type=code&approval_prompt=auto&client_id=1751255441776653&redirect_uri=https%3A%2F%2Fshoppingmall-local.ventajon.com

but I am not able to make it work, also tried to make urldecode function on: `$provider->getAuthorizationUrl()` but still get the same error.

I attach an image with the trace.

Regards.
![fberror](https://cloud.githubusercontent.com/assets/4679449/22016102/4e8a3e92-dca5-11e6-924e-499b45140741.PNG)

**Comment by SammyK** [comment]
Hey @norbertogomez! What do you have listed in [your app's settings](https://developers.facebook.com/apps/1751255441776653/settings/) under the "App Domains" and "Site URL" fields? Also - in the [Facebook Login settings](https://developers.facebook.com/apps/1597341547255440/fb-login/), do you have anything listed under the "Valid OAuth redirect URIs" field?
