### ISSUE TITLE
Unable to specify custom fields

### ISSUE THREAD

**Issue by araratpoghosyan** [thephpleague/oauth2-facebook#32]
in League\OAuth2\Client\Provider\Facebook.php line 103 we have this code:

$fields = [
            'id', 'name', 'first_name', 'last_name',
            'email', 'hometown', 'picture.type(large){url,is_silhouette}',
            'cover{source}', 'gender', 'locale', 'link', 'timezone', 'age_range'
        ];

I am unable to add other fields, like birthday.

Thank you.

**Comment by SammyK** [comment]
Hey @araratpoghosyan! The fields you listed provide some default values that don't require extra permission to access. The oauth2-facebook package is designed to help you easily obtain an access token and then leaves it up to you to [make authenticated requests however you like](https://github.com/thephpleague/oauth2-facebook#getting-additional-data).

If you've requested access to a field that requires extra permissions, you can just send an authenticated request with the fields you would like to receive.

Assuming you've requested the [`user_birthday` permission](https://developers.facebook.com/docs/facebook-login/permissions#reference-user_birthday).

```php
use League\OAuth2\Client\Provider\Facebook;
use League\OAuth2\Client\Provider\AppSecretProof;

$baseUrl = Facebook::BASE_GRAPH_URL.'v2.8';
$appSecretProof = AppSecretProof::create($config['app_secret'], $token->getToken());
$params = http_build_query([
	'fields' => 'id,name,birthday',
	'access_token' => $token->getToken(),
	'appsecret_proof' => $appSecretProof,
]);
$response = file_get_contents($baseUrl.'/me?'.$params);

// Raw JSON response from the Graph API
var_dump($response);
// Response as a plain-old PHP array
$data = json_decode($response, true);
var_dump($data);
```
