### ISSUE TITLE
[Question] Handling `error_code` and `error_message`

### ISSUE THREAD

**Issue by hellboy81** [thephpleague/oauth2-facebook#34]
Should I handle response with `error_code` and `error_message` separately or `oauth2-facebook` API is not up-to-date?

**Comment by SammyK** [comment]
Hey @hellboy81! Error responses should throw an `IdentityProviderException`. The way the provider knows there was an error is that it checks for the `error` key which is the [documented way Graph returns errors](https://developers.facebook.com/docs/graph-api/using-graph-api#errors). Are you receiving an error response that is not namespaced under the `error` key? If so, how are you generating the error?

**Comment by hellboy81** [comment]
>Error responses should throw an IdentityProviderException.

Yes.. But partially... 

This error response is generated by `facebook`: the callback url itself and 

Who should I handle error response this type?

````
{
"error_code"=>"2", 
"error_message"=>"Sorry, this feature isn't available right now: An error occurred while processing this request. Please try again later.",
"state"=>...
}
````
As I mentioned error responses this type are not handled by provider.

**Comment by SammyK** [comment]
Yes, that would be an unsupported error response. But we'll need to add support for it if Graph is returning it. What process are you implementing that is causing this error? I'd like to try to repeat this issue on my end.

**Comment by hellboy81** [comment]
see screenshot:

[img]http://i.imgur.com/5FDIzaY.png[/img]

**Comment by hellboy81** [comment]
OK, I understand: `error_code` and `error_message` should be handled by **your** provider
