### ISSUE TITLE
Add gitter chat

### ISSUE THREAD

**Issue by hellboy81** [thephpleague/oauth2-facebook#35]
Please add gitter chat

**Comment by SammyK** [comment]
Hey @hellboy81! You can use the Gitter chat for the main oauth2-client here: https://gitter.im/thephpleague/oauth2-client. I don't have any plans for creating one specifically for oauth2-facebook as the messages usually go unanswered from what I've seen. Of course if you have an issue, you're always welcome to submit them to the issues here on GitHub. :)
