### ISSUE TITLE
Facebook::checkResponse is incompatible with AbstractProvider::checkResponse

### ISSUE THREAD

**Issue by patrickconroy** [thephpleague/oauth2-facebook#4]
Hello. Right now the master version of `Facebook::checkResponse` type hints the `$response` as an array but its parent doesn't, which causes a fatal error.

https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L559
https://github.com/thephpleague/oauth2-facebook/blob/master/src/Provider/Facebook.php#L115

I don't know which one's wrong/right, so figured I'd just open an issue about it instead of making a PR.

Thanks

**Comment by SammyK** [comment]
Thanks for the heads up @patrickconroy! There have been some major overhaul changes to the parent client repo. I'll make sure these are in sync. :)

**Comment by ramsey** [comment]
Parent repo is settling down, I think. The `master` branch is now 1.0.x-dev, btw.

**Comment by SammyK** [comment]
Sweet - thanks @ramsey!

**Comment by patrickconroy** [comment]
Thanks guys! Sorry for jumping the gun, I guess I just happened to notice this stuff in the middle of everything.

**Comment by SammyK** [comment]
Don't apologize - thanks for finding the issue! :)

**Comment by SammyK** [comment]
This issue is fixed now! But there is another issue with the main repo related to Facebook responses. Sending a PR soon. :)

**Comment by patrickconroy** [comment]
Awesome thank you!

**Comment by patrickconroy** [comment]
Thanks @SammyK , just noticed it looks like the same thing for Google @ https://github.com/thephpleague/oauth2-google/blob/master/src/Provider/Google.php#L70

**Comment by SammyK** [comment]
@patrickconroy Yeah, I suspect several of the providers running on the dev version of the OAuth 2.0 Client will have this issue. Feel free to open an issue for any you find in the respective repo! :)

**Comment by patrickconroy** [comment]
OK will do, @SammyK . The google one in particular looks like it's calling an undefined method, `httpBuildQuery`.
