### ISSUE TITLE
Bio field is deprecated for versions v2.8

### ISSUE THREAD

**Issue by himanshu-dixit** [thephpleague/oauth2-facebook#41]
I'm using latest version of the oauth2-facebook but even with GraphAPIVersion 2.4. I'm getting following error.
```
League\OAuth2\Client\Provider\Exception\IdentityProviderException: OAuthException: (#12) bio field is deprecated for versions v2.8 and higher in League\OAuth2\Client\Provider\Facebook->checkResponse() (line 156 of vendor/league/oauth2-facebook/src/Provider/Facebook.php).
```

**Comment by SammyK** [comment]
What version of oauth2-facebook are you using? There was a patch that might have affected this issue. Try installing the latest version of v1 or v2 and see if that fixes it. I'll close for now but let me know if we need to reopen. :)
