### ISSUE TITLE
graph fields no way to add a new field

### ISSUE THREAD

**Issue by prisis** [thephpleague/oauth2-facebook#42]
Hey :), 
are you accepting a pr with new functions, like addField and getFields?

**Comment by Chrico** [comment]
I would not go that way to change the object itself after instantiation via `addField`. It should stay immutable. Better solution would be to use:

1. a new property `$defaultFields` which contains the fields from `Facebook::getResourceOwnerDetailsUrl`
2. allow a new key `fields` in `$options` in class constructor to merge with defaultFields
3. Use the  `$this->fields` in `Facebook::getResourceOwnerDetailsUrl` and remove the `$fields`.
4. Remove the `< 2.8`-check.

```php
class Facebook extends AbstractProvider
{

	protected $fields = [];
	
	protected $defaultFields = [
		'id', 
		'name', 
		'first_name', 
		'last_name',
		'email', 
		'hometown', 
		'picture.type(large){url,is_silhouette}',
		'cover{source}', 
		'gender', 
		'locale', 
		'link', 
		'timezone', 
		'age_range'
	];

	/* snip*/

	public function __construct($options = [], array $collaborators = [])
    {
        parent::__construct($options, $collaborators);
		
		
		if (isset($options[ 'fields' ] && is_array( $options[ 'fields' ]) {
			$this->fields = array_merge($this->defaultFields, $options[ 'fields' ]);
		}

		/* snip*/
	}

}
```

secondly the version check for `< 2.8` should be removed. We're already in version 2.11 and everyone who wants to use the `bio` field with an old Graph API Version can add it on it's own. Having such "old" checks will just mess up with the code base.
