### ISSUE TITLE
Blank page for all apple users?

### ISSUE THREAD

**Issue by DeanoAus** [thephpleague/oauth2-facebook#43]
Hey guys,

My Flarum is here : https://www.flashover.com.au/flarum/ and for android and PC users, they can use your extension without issue.

For *all* apple users, they are served a blank page. When debug is enabled, they get this.
https://www.flashover.com.au/flarum/images/IphoneError.jpg

**Comment by luceos** [comment]
@DeanoAus thank you for your report. Sadly the author of this package has no relation with Flarum whatsoever. The Flarum facebook extension uses this package, but the author of this package is not responsible for its implementation. 

Please close this issue and follow the activity on [discuss](https://discuss.flarum.org/d/8678-facebook-auth-not-working-for-apple-devices) for more information.
