### ISSUE TITLE
FacebookUser api change

### ISSUE THREAD

**Issue by bogdan-pistol** [thephpleague/oauth2-facebook#44]
It appears that the Facebook graph API changed because I get this exception (when using with knpuniversity/oauth2-client-bundle):

`string(74) "OAuthException: (#12) bio field is deprecated for versions v2.8 and higher"`

The `\League\OAuth2\Client\Provider\FacebookUser `has a **bio** field that has been removed. Is there a way to override this class, or remove the bio field from the request?

**Comment by bogdan-pistol** [comment]
Was due to the api version specified in the `knpu_oauth2_client` config.
closing issue

**Comment by shadowhand** [comment]
The `graphApiVersion` can be used to control this. The `FacebookUser::getBio()` method has been deprecated.
