### ISSUE TITLE
access to full ressource owner response data

### ISSUE THREAD

**Issue by kaiserlos** [thephpleague/oauth2-facebook#6]
Hi,

I want to cache the ressource owner response data and are missing the toArray function as implemented in the GenericResourceOwner. 

I know it's not part of the interface but as the data is protected in the FacebookUser class I don't see any other way to get the full userdetails response without making an other request at the moment. Is there any reason to not implement the toArray function?

**Comment by SammyK** [comment]
Good call! Added in [0.0.12](https://github.com/thephpleague/oauth2-facebook/releases/tag/0.0.12). :)
