### ISSUE TITLE
OAuthException: (#200) Missing Permissions

### ISSUE THREAD

**Issue by burgoyn1** [thephpleague/oauth2-facebook#61]
I just started getting this error about 45 minutes ago. I think facebook updated again.

**Comment by burgoyn1** [comment]
Yup, same as last time but instead it is the 'link' parameter in the getResourceOwnerDetailsUrl function. It needs to be taken out then works properly.

**Comment by JosefBanya** [comment]
For hotfix require this PR -> f09626c648563956dd94d337d5d542d07273fe55

**Comment by Nefro9** [comment]
Will be nice to allow rewrite fields on config

**Comment by Grummfy** [comment]
apparently it's all "link, age_range et gender."
