### ISSUE TITLE
Force to HTTPS issue

### ISSUE THREAD

**Issue by fatihyilmazz** [thephpleague/oauth2-facebook#69]
Hi, i made a facebook login on symfony project. It works on test servers but it doesnt work on live server. 
Here is my connectAction function
![connectAction](https://user-images.githubusercontent.com/17908628/118610320-5015a180-b7c4-11eb-8b43-8823b542651e.PNG)
It returns url with https on test servers. But it returns url with http in live server. I tried to add redirect_uri to options like 
.... , [ 'redirect_uri' => 'https://www.xxlive-serverxx.com/connect/facebook/check',
'auth_type' => 'rerequest'
]... but it returns another error which is 'OAuthException: URL cannot be loaded: The domain of this URL has not been added to the domains of this app. Add all domains and subdomains of your app to the App Domains field in your app's settings to load this URL.'. I checkout the authorization urls in facebook developer page and my live server url is added with https.

**Comment by shadowhand** [comment]
There is nothing in this package that uses a non-secure HTTP URI. I don't know what `ClientRegistry` class is, but it appears to be something not part of this package.

We will need more information to determine if it is an issue with this package.
