### ISSUE TITLE
Handle exception when the user denies access to email.

### ISSUE THREAD

**Issue by vipconsult** [thephpleague/oauth2-facebook#7]
when user doesn't allow email to be passed it should handle the exception based on the info here:

https://developers.facebook.com/docs/facebook-login/permissions/v2.2#checking

i think the best approach woule be to thow an exception so that i can display something like

"To use the facebook login you must share your email! click here to reauthorize!"

https://developers.facebook.com/docs/facebook-login/login-flow-for-web/v2.2#re-asking-declined-permissions

**Comment by SammyK** [comment]
This check should be done on the app side, not in this project.

After obtaining a user access token, send a request to the [`/me/permissions` endpoint](https://developers.facebook.com/docs/graph-api/reference/user/permissions/) and check for whatever permission your app requires. If the user denied the permission, you'll need to display a message to the user and generate a [re-request URL](https://developers.facebook.com/docs/facebook-login/permissions/v2.4#handling) ([different from the initial authorization URL](https://developers.facebook.com/docs/facebook-login/login-flow-for-web/v2.4#re-asking-declined-permissions)) asking for the permission again.

**Comment by vipconsult** [comment]
this condition is specific to the facebook api and as far as i know all other providers supply the email regardless.

so in my case i have a code which handles many providers and creating something specific to facebook will force me to put many if else statements to handle the response for each provider.

**Comment by SammyK** [comment]
> this condition is specific to the facebook api

Correct.

> creating something specific to facebook will force me to put many if else statements to handle the response for each provider.

I'm not sure how your app is architected but if you've got a service class that handles all the providers you might create one for Facebook that extends from the main on with the Facebook-specific logic.

But again - this is all stuff that should be checked on your app side and not coded into the provider since it's a unique use-case. :)
