### ISSUE TITLE
Make getBaseFacebookUrl() and getBaseGraphUrl() protected or public

### ISSUE THREAD

**Issue by mlncn** [thephpleague/oauth2-facebook#73]
In a lightweight [facebook API](https://gitlab.com/agaric/php/php-facebook) we are extending oauth2-facebook

Would a pull request to make the `getBaseFacebookUrl()` and `getBaseGraphUrl()` methods "public" be accepted?  How about at least only "protected"?

They are getter wrappers for public variables, after all.

Thanks!

**Comment by shadowhand** [comment]
Public, no. Protected, yes.
