### ISSUE TITLE
i got blank page after login

### ISSUE THREAD

**Issue by Ferdinandgushcloud** [thephpleague/oauth2-facebook#76]
Hi all, i got blan page after login. i'm using graph version v16.0 and my PHP version 8.1.7.  
my permissions are pages_manage_metadata, pages_manage_posts, pages_read_engagement, pages_show_list

here is the URL after login but display blank page.
`https://www.facebook.com/v16.0/dialog/oauth?scope=pages_manage_metadata%2Cpages_manage_posts%2Cpages_read_engagement%2Cpages_show_list&state=xxxx&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Ftesting-ferdi.ap.ngrok.io%2Ffacebook%2Fcallback&client_id=xxx&ret=login&fbapp_pres=0&logger_id=xxx-xxx-xx&tp=unspecified&cbt=xxx&ext=xxx&hash=xxxx`

How to fix this? please advice.

**Comment by shadowhand** [comment]
We are not able to help with debugging, especially with so little information.
