### ISSUE TITLE
Symfony deprecation-contracts needs php 8.1

### ISSUE THREAD

**Issue by VanShane** [thephpleague/oauth2-facebook#77]
Hi, I noticed one of the dependencies needed for this project has a minimum php requirement of php 8.1, is there any way to circomvent this problem ?

![image](https://github.com/thephpleague/oauth2-facebook/assets/58779122/35c8cb19-8058-4f22-b25c-f39725a8faea)

**Comment by shadowhand** [comment]
So long as you install the package in a system that is using PHP 7.3, Composer should pick a supported version.

However, PHP 7.x has been EOL for a long while, and PHP 8.0 is [EOL as of today](https://www.php.net/eol), so it is probably better to focus switching to a supported version.
