### ISSUE TITLE
Create a demo?

### ISSUE THREAD

**Issue by shadowhand** [thephpleague/oauth2-facebook#9]
If you want to, it would be really easy to add Facebook to my [oauth2-demos](/shadowhand/oauth2-demos) repository. You should be able to tag a `1.0.0-betaX` release and include it by modifying the `example.env` and the `composer.json`.

**Comment by SammyK** [comment]
Sounds good! I'll give this a gander maybe tomorrow sometime. :)

**Comment by SammyK** [comment]
I just pushed up a `1.0.0-alpha1` tag. Will that work?

**Comment by shadowhand** [comment]
Works great! Only one problem... some providers have started using `toArray` in their owner (user) classes, and Facebook uses `asArray` which makes things difficult. As a solution to this, I've created thephpleague/oauth2-client#398.

**Comment by SammyK** [comment]
Updated in `1.0.0-alpha2`. :)

**Comment by shadowhand** [comment]
I'm using `~1.0` flag, update should be automatic. :)
